CC = cc
FLAGS = -Wall -Wextra -Werror

NAME = libftprintf.a

SRCS = ft_printf.c \ft_putstr.c \ ft_putchar.c \
		ft_putnbr.c \ ft_puthex \ ft_putptr

OBJS = ${SRCS:.c=.o}

all: $(NAME)

clean:
	rm -f $(OBJS)
fclean:
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
